[#133559651] MySql findWhereEq
influentialpublishers/kuss pull request #25
Opened 2016-11-19 01:44 UTC by jonajonlee

2016-11-19 03:12 UTC, mattsmee approved these changes
:shipit:

2016-11-19 05:12 UTC, jxbadam requested changes

2016-11-19 05:12 UTC, jxbadam commented on test/lib/mysql/index.spec.js
> +      , sort       : { id : 'desc' }
If sort is an object this is bad.

How do we do multiple sorts (for instance last_name DESC, first_name DESC, id ASC)? 
Key ordering in objects is not guaranteed. We may need to use a tuple.

2016-11-19 18:44 UTC, scull7 commented on test/lib/mysql/index.spec.js
> +      , sort       : { id : 'desc' }
I'm sorry I missed that @jonajonlee !  We should be using a tuple like so:

``` javascript
const query = {
  projection: [ 'id', 'traversal_id', 'network_type_code' ]
, predicates : { stored_es : 1479439176, deleted : 0 }
, sort: [ {"id": "desc"} ]
}

```

2016-11-22 00:56 UTC, jonajonlee commented on test/lib/mysql/index.spec.js
> +      , sort       : { id : 'desc' }
@jxbadam @scull7 fixed. please review

2016-11-22 00:59 UTC, scull7 approved these changes

2016-11-22 00:59 UTC, merged