Updates got-couch to 1.1.2
influentialpublishers/kuss pull request #38
Opened 2016-12-10 01:33 UTC by mszymulanski

2016-12-11 23:22 UTC, jxbadam approved these changes
:shipit: :fire:

2016-12-13 02:06 UTC, jonajonlee commented on lib/couchdb/index.js
> +const del = R.curry((couch, bucket, id, rev) => couch.del(bucket, id, rev))
this should be deleteById

2016-12-13 02:27 UTC, jonajonlee requested changes

2016-12-13 02:27 UTC, jonajonlee commented on lib/couchdb/index.js
> +const del = R.curry((couch, bucket, id, rev) => couch.del(bucket, id, rev))
probably something along the lines of this

```javascript
const deleteById = R.curry((couch, bucket, id) =>
  couch.getById(couch, id)
  .then(R.prop('_rev_id')
  .then(couch.deleteByIdAndRevId(couch, bucket, id))
)

2016-12-13 02:27 UTC, jonajonlee commented on lib/couchdb/wrapper.js
> +const del = wrapper((couch, bucket, id, rev) =>
this should be called deleteByIdAndRevId

2016-12-13 02:27 UTC, jonajonlee commented on lib/memory/index.js
> +  const del = R.curry((bucket, id) =>
Change all of these `del` functions of the Kuss interfaces to `deleteById` to be more explicit

2016-12-13 02:27 UTC, jonajonlee commented on lib/couchdb/index.js
> +const del = R.curry((couch, bucket, id, rev) => couch.del(bucket, id, rev))
it should also throw the NotFound error if getById returns nothing.

2016-12-13 02:27 UTC, jonajonlee commented on lib/memory/index.js
> +      .tap(R.when(R.isNil, () => Err.NotFound.throw(STORE, bucket, id)))
👍

2016-12-13 02:27 UTC, jonajonlee commented on lib/couchdb/index.js
> +const del = R.curry((couch, bucket, id, rev) => couch.del(bucket, id, rev))
noticed the MemoryStore.deleteById returns true on successful delete. This one should also return true in the same case

2016-12-13 04:37 UTC, merged