Adds a deleteById to kuss.
influentialpublishers/kuss pull request #41
Opened 2016-12-15 22:03 UTC by mszymulanski

2016-12-15 22:17 UTC, scull7 approved these changes

2016-12-15 23:04 UTC, jxbadam approved these changes
:shipit: 🔥

2016-12-16 00:45 UTC, jonajonlee requested changes
unify errors of deleteById across the stores

2016-12-16 00:45 UTC, jonajonlee commented on lib/mysql/index.js
> +)
this should throw a NotFound error like the other stores if the id does not exist.

2016-12-16 01:58 UTC, jonajonlee approved these changes
:shipit:

2016-12-16 20:34 UTC, scull7 approved these changes
:shipit:

2016-12-16 20:34 UTC, merged